server:
  port: 9010
  servlet:
    multipart:
      maxFileSize: 2MB
      maxRequestSize: 100MB

spring:
  datasource:
    url: jdbc:mysql://192.168.10.75:3306/project?useUnicode=ture&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: 3785*

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/dayte/
      suffix: .jsp
    converters:
      preferred-json-mapper: gson



  security:
    user:
      name: user
      password: 1111

    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            client-id: 3af33602bcd918bdbedb87160f04afea
            redirect-uri: http://localhost:9010/login/oauth2/code/kakao
            client-secret: dOHtmglwKUXRZFxmU1Xfg3xhv3qoPDgK
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

          google:
            client-id: 319783684140-prefoqa00knmkcrlsnefnjg4t7bvs99f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:9010/login/oauth2/code/google
            scope:
              - profile
              - email
#            구글은 기본으로 설정된 grant-type 이 authorization_code 인듯함
#            authorization-grant-type:

          naver:
            client-name: Naver
            client-id: kRhX2HahioyS7fqh8MUf
            client-secret: EDd4futKWc
            redirect-uri: http://localhost:9010/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile_image


  mail:
    host: smtp.gmail.com
    port: 587
    username: j2studio.jungie2@gmail.com
    password: nzwttixznzahtuva
    properties:
      mail:
        smtp:
          ssl: enable
          auth: true
          starttls:
            required: true


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        security: trace


