server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://192.168.10.75:3306/project?useUnicode=ture&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: 3785*

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/project/
      suffix: .jsp

  security:
    user:
      name: user
      password: 1111


  mail:
    host: smtp.gmail.com
    port: 587
    username: j2studio.jungie2@gmail.com
    password: nzwttixznzahtuva
    properties:
      mail:
        smtp:
          ssl: enable
          auth: true
          starttls:
            required: true


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        security: trace


